tasks:
  - init: |
      gp open README.md
  - name: Initialize 
    command: |
       echo "Almost ready"

ports:

  # OpenTelemetry Demo WebStore
  - port: 8080
    onOpen: open-preview
    visibility: public

  # Prometheus
  - port: 9090
    onOpen: open-preview
    visibility: public

  # Jaeger
  - port: 49153
    onOpen: open-preview
    visibility: public
    
  # Jaeger OTLP Collector
  - port: 4317
    onOpen: ignore
    visibility: public

  # Grafana
  - port: 49156
    onOpen: open-preview
    visibility: public

  # Locust - Load Generation
  - port: 49173
    onOpen: open-preview
    visibility: public
    

vscode:
  extensions:
    - ms-azuretools.vscode-docker    