tasks:
  - init: |
      git clone --branch Shahmaran https://git@github.com:devrimdemiroz/opentelemetry-demo-webstore.git
      gp open README.md
  - name: Initialize standalone Node Application 
    command: |
       echo "Installing dependencies for ToDo API node app"
       cd app
       npm install
  - name: Initialize OpenTelemetry demo
    command: |
       echo "Running OpenTelemetry demo"
       cd opentelemetry-demo/
       sleep 5s &&
       docker compose up --no-build
      

ports:

  # OpenTelemetry Demo WebStore
  - port: 8080
    onOpen: open-preview
    visibility: public

  # Prometheus
  - port: 9090
    onOpen: open-preview
    visibility: public

  # Jaeger
  - port: 49153
    onOpen: open-preview
    visibility: public
  
  # Jaeger Standalone
  - port: 16686
    onOpen: open-browser
    visibility: public
    
  # Jaeger OTLP Collector
  - port: 4317
    onOpen: ignore
    visibility: public

  # Grafana
  - port: 49156
    onOpen: open-preview
    visibility: public

  # Locust - Load Generation
  - port: 49173
    onOpen: open-preview
    visibility: public
    

vscode:
  extensions:
    - ms-azuretools.vscode-docker    