tasks:
  - init: |
      mkdir /workspace/signoz
      cd /workspace/signoz
      git clone -b main https://github.com/SigNoz/signoz.git && cd signoz/deploy/
      docker-compose -f docker/clickhouse-setup/docker-compose.yaml up -d
      # open the readme document in VS Code
      gp open README.md
      docker pull mysql:latest
      docker run --name your-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mysecretpassword -d mysql:latest
      docker run --name your-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres
  - name: Initialize 
    command: |
       echo "Almost ready"

vscode:
  extensions:
    - ms-azuretools.vscode-docker    